# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod 元数据
mod_version=2.1.0
maven_group=com.shadowslice
archives_base_name=autotntcart

# Minecraft
minecraft_version=1.21.1
java_version=21

# Architectury API
architectury_api_version=13.0.11

# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.116.17+1.21.1

enabled_platforms=fabric,neoforge
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
cloth_config_version=15.0.140
modmenu_version=11.0.3